server:
  port: 8082
spring:
  profiles:
    active: prod
token:
  user: userToken
  resource: rescToken
account:
  loginurl: dengludizhi
  logouturl: logouturl
decoder:
  des:
    key: a@9*!ap%
