debug: true
web:
  app:
    gl: D:/Github/abc/
  ssm:
    file: D:/Github/abc/MoblieMessage.properties
feign:
  datacache:
    url: http://39.106.168.77:8080
    snapshots:
      path: /output/devices
      p1: ids
      p2: p2
      p3: p3
    deviceinfo:
      path: /output/device
      p1: id
      p2: p2
      p3: p3
    find:
      path: /device/find
      p1: ids
    get:
      path: /device/get
      p1: id
  datamanage:
    url: http://39.106.168.77:8081
    device:
      path: ${feign.datamanage.url}/device
      find:
        path: ${feign.datamanage.device.path}/suffix
    employee:
      path: ${feign.datamanage.url}/employee
      create:
        path: ${feign.datamanage.employee.path}/create
      find:
        path: ${feign.datamanage.employee.path}/find
      changePassword:
        path: ${feign.datamanage.employee.path}/changePassword