web:
  app:
    gl: /home/java_server/dataoutput/app/gl/
  ssm:
    file: /home/java_server/dataoutput/ssm/MoblieMessage.properties
feign:
  datacache:
    url: http://127.0.0.1:8080
    snapshots:
      path: /output/devices
      p1: ids
      p2: p2
      p3: p3
    deviceinfo:
      path: /output/device
      p1: id
      p2: p2
      p3: p3
    find:
      path: /device/find
      p1: ids
    get:
      path: /device/get
      p1: id
  datamanage:
    url: http://127.0.0.1:8081
    device:
      path: ${feign.datamanage.url}/device
      find:
        path: ${feign.datamanage.device.path}/find
    employee:
      path: ${feign.datamanage.url}/employee
      create:
        path: ${feign.datamanage.employee.path}/create