debug: true
feign:
  datacache:
   url: http://127.0.0.7:8080/datacache
   snapshots:
    path: /output/devices
    p1: ids
    p2: p2
    p3: p3
   deviceinfo:
    path: /output/device
    p1: id
    p2: p2
    p3: p3